name: Add Gradle Wrapper

on:
  workflow_dispatch: # 手動実行

jobs:
  add-gradlew:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Generate Gradle Wrapper
        run: |
          # gradlewが既にあれば何もしない
          if [ ! -f gradlew ]; then
            gradle wrapper
          fi

      - name: Commit and push Gradle Wrapper
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add gradlew gradlew.bat gradle/wrapper/*
          git commit -m "Add Gradle Wrapper files (via GitHub Actions)" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
