name: Build and Upload Mod

on:
  push:
    branches:
      - main  # mainブランチにpushされた時に実行

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # リポジトリのコードをチェックアウト
    - name: Checkout code
      uses: actions/checkout@v2

    # JDKのセットアップ
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    # Mavenを使用してビルド
    - name: Build with Maven
      run: mvn clean install

    # ビルドしたJARファイルをGitHub Releaseにアップロード
    - name: Upload JAR to GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: target/*.jar  # ビルドされたJARファイルをアップロード
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}  # GitHub SecretsのTOKENを使用
