name: Build and Upload Mod

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # リポジトリをチェックアウト (secrets.TOKEN を使用)
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.TOKEN }}

      # JDK 17をセットアップ (temurinを指定)
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      # Gradleでビルド
      - name: Build with Gradle
        run: ./gradlew build

      # ビルドされたJARをアーティファクトとしてアップロード (secrets.TOKEN を使用)
      - name: Upload JAR as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: mod-jar
          path: build/libs/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
